# Use XeLaTeX
$pdf_mode = 5;

# Run makeglossaries when .glo or .acn files change
add_cus_dep('glo', 'gls', 0, 'run_makeglossaries');
add_cus_dep('acn', 'acr', 0, 'run_makeglossaries');

sub run_makeglossaries {
    my ($base) = @_;
    return system("makeglossaries \"$base\"");
}
